### ISSUE TITLE
Getting width in the graph?

### ISSUE THREAD

**Issue by Qiming-C** [MatveiT/GraphFromOSM#3]
Hi, I was wondering if the graph can be weighted graph? which the width consider to be the distance between two vertices

**Comment by Qiming-C** [comment]
nvm, I found out the issue lol

**Comment by MatveiT** [comment]
Hi,

Great. :)
I guess you may already know it, but the distance of an edge is computed as
the sum on all its LineString segments of the Haversine function (lng1,
lat1 lng2, lat2) -> dist.

Matvei

**Comment by Qiming-C** [comment]
I was gonna use "width" from tags attribute. Do you know if that is presented as distance between 2 nodes?

**Comment by MatveiT** [comment]
Hi,
As far as I remembre, "width" is a tag from "geojson.io" used for display
the edges.
So probably it is better to vreate another tag for distance.
